version: '3.6'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: dikuznetsov/foodgram-project:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - static_value:/var/html/static/

      - media_value:/var/html/media/

    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/var/www/html --email dkuznetsov27@gmail.com --agree-tos --no-eff-email --staging -d dikuznetsov-foodgram.cf  -d www.dikuznetsov-foodgram.cf

volumes:
  postgres_data:
  static_value:
  media_value:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/dikuznetsov/foodgram-project/static/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/dikuznetsov/foodgram-project/dhparam/
      o: bind