# Generated by Django 3.2.1 on 2021-05-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_cart_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_cart_user_recipe',
        ),
    ]
